# .lefthook.yaml
---
pre-commit:
  parallel: true
  jobs:
    - name: go
      group:
        jobs:
          - run: gofumpt -l -w .
          - run: goimports -w .
          - run: staticcheck ./...
          - run: go vet ./...
    - name: md-lint
      glob: "*.md"
      run: markdownlint {staged_files} --disable MD013
    - name: yaml-lint
      glob: "*.{yml,yaml}"
      run: yamllint --no-warnings {staged_files}
    - name: json-lint
      glob: "*.json"
      run: jsonlint {staged_files} --no-duplicate-keys --compact --quiet
